docs:Update readme
exoplanet-dev/jaxoplanet pull request #135
Opened 2024-02-24 20:44 UTC by soichiro-hattori

Starting a draft PR to address #122 and update the `README.md` file. To avoid having to maintain two duplicates of an intro doc, the `README.md` will be the file with content and `index.md` will simply keep track of the `README.md` file.

2024-02-24 22:45 UTC, soichiro-hattori commented
@dfm: Here's a draft version of the new README/RTD landing page!
I'm not entirely sure, but I think we might need to think about using absolute file paths when creating references since the `README.md` & `index.md` file exist in different directories?
Also, would the toctree render in the README on Github?

2024-02-24 23:22 UTC, dfm requested changes
Looks great! One tiny comment then I think we should merge.

2024-02-25 05:42 UTC, soichiro-hattori commented on README.md
> +```
Great that's what I was also thinking!

2024-02-25 05:43 UTC, soichiro-hattori commented
@dfm: There still isn't any text in the "Quick Start" part of the `README.md` file but otherwise I think it's ready to go for now!

2024-02-26 14:57 UTC, merged